# Generated by Django 3.2.5 on 2021-07-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='아이다어명을 입력하세요', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_image/%Y/%m/%d/')),
                ('desc', models.TextField(help_text='아이디어에 대한 설명을 적어주세요')),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
