# Generated by Django 3.2.5 on 2021-07-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_idea_devtools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='devtools',
            new_name='devtool',
        ),
    ]
