# Generated by Django 3.2.5 on 2021-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_rename_devtools_idea_devtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(blank=True, help_text='아이디어에 대한 설명을 적어주세요'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(null=True, upload_to='idea_image/%Y/%m/%d/'),
        ),
    ]
